# baseURL: http://dev.mathematicalmichael.com
baseURL: https://mpilosov.com
languageCode: en-us
title: "Mathematical Michael"
theme: dimension
Params:
  author: Michael Pilosov
  url: https://github.com/mathematicalmichael
  logo: icons/mult.svg
