#baseURL: http://clfx.cc/mm/
baseURL: "http://dev.mathematicalmichael.com/"
languageCode: en-us
title: "My New Hugo Site"
theme: dimension
Params:
  author: Michael Pilosov
  url: https://github.com/mathematicalmichael
  logo: icons/mult.svg
